name: Thanos merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-thanos.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-thanos.yaml'
jobs:
  thanos-merge:
    uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream: thanos-io/thanos
      downstream: openshift/thanos
      sandbox: rhobs/thanos
      go-version: "1.22"
      restore-upstream: >-
        CHANGELOG.md
        VERSION
        docs
        go.mod
        go.sum
        pkg
        tutorials
        .busybox-versions
        .devcontainer
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
