name: Prometheus Operator merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' #@hourly
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-prometheus-operator.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-prometheus-operator.yaml'
jobs:
  prometheus-operator-merge:
    uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream: prometheus-operator/prometheus-operator
      downstream: openshift/prometheus-operator
      sandbox: rhobs/prometheus-operator
      go-version: "1.22"
      restore-upstream: >-
        CHANGELOG.md
        Documentation
        VERSION
        bundle.yaml
        example
        go.mod
        go.sum
        pkg
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
