name: Node exporter merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-node-exporter.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-node-exporter.yaml'
jobs:
  node-exporter-merge:
    uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream: prometheus/node_exporter
      downstream: openshift/node_exporter
      sandbox: rhobs/node_exporter
      restore-downstream: >-
         OWNERS
      restore-upstream: >-
         CHANGELOG.md
         VERSION
         collector
         go.mod
         go.sum
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
