name: metrics-server merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily

jobs:
  metrics-server-merge:
    uses: rhobs/syncbot/.github/workflows/merge-flow.yaml@main
    with:
      upstream: kubernetes-sigs/metrics-server
      downstream: openshift/kubernetes-metrics-server
      sandbox: rhobs/kubernetes-metrics-server
      go-version: 1.20
      # restore-upstream:
      restore-downstream: OWNERS charts/OWNERS
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
